# Generated by Django 4.0.4 on 2023-03-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='captcha',
            name='incorrect',
            field=models.IntegerField(default=0),
        ),
    ]
