# Generated by Django 4.0.4 on 2022-05-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('log_channel', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=30, null=True)),
                ('username', models.CharField(max_length=30, null=True)),
                ('link', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
    ]
