# Generated by Django 4.0.4 on 2022-05-21 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_group_group_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('can_manage_chat', models.BooleanField(default=False)),
                ('can_delete_messages', models.BooleanField(default=False)),
                ('can_manage_video_chats', models.BooleanField(default=False)),
                ('can_restrict_members', models.BooleanField(default=False)),
                ('can_promote_members', models.BooleanField(default=False)),
                ('can_change_info', models.BooleanField(default=False)),
                ('can_post_messages', models.BooleanField(default=False)),
                ('can_edit_messages', models.BooleanField(default=False)),
                ('can_invite_users', models.BooleanField(default=False)),
                ('can_pin_messages', models.BooleanField(default=True)),
                ('is_anonymous', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialGroup',
            fields=[
                ('group_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, null=True)),
                ('username', models.CharField(max_length=30, null=True)),
                ('link', models.CharField(max_length=30, null=True)),
                ('permission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.privilege')),
            ],
        ),
    ]
