# Generated by Django 4.0.4 on 2022-05-21 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_privilege_specialgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialgroup',
            old_name='permission',
            new_name='privilege',
        ),
    ]
