# Generated by Django 4.0.4 on 2022-05-21 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_rename_permission_specialgroup_privilege'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('can_send_messages', models.BooleanField(default=True)),
                ('can_send_media_messages', models.BooleanField(default=False)),
                ('can_send_other_messages', models.BooleanField(default=False)),
                ('can_send_polls', models.BooleanField(default=False)),
                ('can_add_web_page_previews', models.BooleanField(default=False)),
                ('can_change_info', models.BooleanField(default=False)),
                ('can_invite_users', models.BooleanField(default=False)),
                ('can_pin_messages', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.permission'),
        ),
    ]
