# Generated by Django 4.0.4 on 2022-05-23 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_permission_group_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='privilege',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.privilege'),
        ),
        migrations.AddField(
            model_name='specialgroup',
            name='flair',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
