# Generated by Django 4.0.4 on 2022-05-23 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_alter_privilege_can_edit_messages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='privilege',
        ),
        migrations.AddField(
            model_name='group',
            name='admin_privilege',
            field=models.ForeignKey(help_text='Privileges for admins', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='group.privilege'),
        ),
        migrations.AddField(
            model_name='group',
            name='special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='verified_privilege',
            field=models.ForeignKey(help_text='Privileges for verifiedusers', null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.privilege'),
        ),
        migrations.DeleteModel(
            name='SpecialGroup',
        ),
    ]
