# Generated by Django 4.0.4 on 2022-05-24 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_remove_group_privilege_group_admin_privilege_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='admin_privilege',
            field=models.ForeignKey(blank=True, help_text='Privileges for admins', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='group.privilege'),
        ),
        migrations.AlterField(
            model_name='group',
            name='link',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='log_channel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.permission'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='verified_privilege',
            field=models.ForeignKey(blank=True, help_text='Privileges for verifiedusers', null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.privilege'),
        ),
    ]
