# Generated by Django 4.0.4 on 2022-07-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_alter_group_admin_privilege_alter_group_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='shortname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
