# Generated by Django 4.0.4 on 2022-07-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_group_shortname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='shortname',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
