# Generated by Django 4.0.4 on 2022-09-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_alter_group_shortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='flair',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
