# Generated by Django 4.0.4 on 2022-09-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0012_group_flair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='flair',
            field=models.CharField(blank=True, default='verified', max_length=30, null=True),
        ),
    ]
