# Generated by Django 4.0.4 on 2022-10-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0013_alter_group_flair'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='special',
            new_name='vendor',
        ),
    ]
