# Generated by Django 4.0.4 on 2022-12-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0014_rename_special_group_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_rule',
            field=models.TextField(null=True),
        ),
    ]
