# Generated by Django 4.0.4 on 2022-12-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0015_group_group_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_rule',
        ),
        migrations.AddField(
            model_name='group',
            name='rules_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
