# Generated by Django 4.0.4 on 2022-12-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0016_remove_group_group_rule_group_rules_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='captcha',
            field=models.BooleanField(default=True),
        ),
    ]
