# Generated by Django 4.0.4 on 2022-12-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0017_group_captcha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='rules_id',
        ),
        migrations.AddField(
            model_name='group',
            name='rules',
            field=models.TextField(blank=True, null=True),
        ),
    ]
