# Generated by Django 4.0.4 on 2023-01-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0018_remove_group_rules_id_group_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='rules_id',
            field=models.IntegerField(null=True),
        ),
    ]
