# Generated by Django 4.0.4 on 2023-01-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0019_group_rules_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='antispam',
            field=models.BooleanField(default=True),
        ),
    ]
