# Generated by Django 4.0.4 on 2023-01-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0020_group_antispam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='rules',
        ),
    ]
