# Generated by Django 4.0.4 on 2023-06-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0021_remove_group_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='flair',
            field=models.CharField(blank=True, default='Verified', max_length=30, null=True),
        ),
    ]
