# Generated by Django 4.0.4 on 2024-06-01 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0022_alter_group_flair'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_limit', models.IntegerField(blank=True, null=True)),
                ('new_line_limit', models.IntegerField(blank=True, null=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
            ],
        ),
    ]
