# Generated by Django 4.0.4 on 2024-06-01 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0023_grouplimits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplimits',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_limits', to='group.group'),
        ),
    ]
