# Generated by Django 4.0.4 on 2024-06-01 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0024_alter_grouplimits_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouplimits',
            old_name='word_limit',
            new_name='character_limit',
        ),
    ]
