# Generated by Django 4.0.4 on 2022-12-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='is_temp',
            field=models.BooleanField(default=False),
        ),
    ]
