# Generated by Django 4.0.4 on 2022-05-21 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_teleuser_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warn_type', models.CharField(default='warn', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_warn', to='user.teleuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warning', to='user.teleuser')),
            ],
        ),
    ]
