# Generated by Django 4.0.4 on 2022-05-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_warning'),
    ]

    operations = [
        migrations.AddField(
            model_name='warning',
            name='reason',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warning',
            name='warn_type',
            field=models.IntegerField(default=0),
        ),
    ]
