# Generated by Django 4.0.4 on 2022-05-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_warning_reason_alter_warning_warn_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warning',
            name='warn_type',
        ),
        migrations.AddField(
            model_name='warning',
            name='banning_warn',
            field=models.BooleanField(default=0),
        ),
    ]
