# Generated by Django 4.0.4 on 2022-05-21 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_warning_warn_type_warning_banning_warn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Warning',
            new_name='Warn',
        ),
    ]
