# Generated by Django 4.0.4 on 2022-05-24 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_teleuserlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teleuserlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='user.teleuser'),
        ),
    ]
