# Generated by Django 4.0.4 on 2022-07-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_teleuserlog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teleuser',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
