# Generated by Django 4.0.4 on 2022-08-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_teleuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='teleuserlog',
            name='event',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
