# Generated by Django 4.0.4 on 2022-10-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_teleuserlog_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teleuser',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='teleuser',
            name='captcha_solved',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='teleuser',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teleuser',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='teleuser',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='teleuser',
            name='keybase',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='teleuser',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='teleuser',
            name='muted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='teleuser',
            name='ph_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teleuser',
            name='verified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
