# Generated by Django 4.0.4 on 2022-11-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_teleuser_active_alter_teleuser_captcha_solved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teleuser',
            name='helper_admin',
            field=models.BooleanField(default=False),
        ),
    ]
