# Generated by Django 4.0.4 on 2023-01-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_teleuser_helper_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='teleuser',
            name='msg_count',
            field=models.IntegerField(default=0),
        ),
    ]
