# Generated by Django 4.0.4 on 2023-03-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_teleuserverifylog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='teleuserverifylog',
            name='event',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
