# Generated by Django 4.0.4 on 2024-02-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_teleuserverifylog_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='teleuser',
            name='verification_expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='teleuser',
            name='verification_expires_thirty_days_notification',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
